### PR TITLE
Added PLUTO (V.4.2) support. The loader passes all (relevant) tests s…

### PR DESCRIPTION
**Pull request by alexziab**
…uccessfully, but the run.py script complains about fargo-related stuff. Commenting out the fargocpt import in run.py returns 0 errors.

The commit also contains a src/PLUTOgrid.py file with some helper functions (I didn't want to clutter the loader) and a test setup under samples/PLUTO42/ (1Mb in size), which corresponds to a Jupiter-like planet in a simple disk (modified from PLUTO's example setups).

### CODE REVIEW

**Comment by rometsch** [comment]
This is a new case where a loader depends on some external file.
I think it is cleaner if they go into the loader directory. To keep it clean and avoid the loaders init function to pick it up, I moved the PLUTOgrid.py into a loaders/PLUTO42aux directory and fixed the imports.

However, on my computer the test fails beacuse "alexpy" can not be imported. I strongly suspect that this is your own personal library :)

Could you include the necessary code in the loader and fix this dependency issue?

**Comment by alexziab** [comment]
Yeah I was using my humble little library for debugging purposes and forgot to remove that, should be fixed now!
You could also move the PLUTOgrid code into the loader and delete the aux directory. It's just that I find it's cleaner this way.

**Comment by rometsch** [comment]
Almost done. I just added the PLUTO loader tests to the tests/run.py file and renamed the auxiliary files.
So now there is only one issue left: there are 2 errors in the test on my computer. Could you investigate this?
 
Here is one of the errors.

`Traceback (most recent call last):
  File "/home/rometsch/repo/simdata/tests/test_loader_PLUTO42.py", line 47, in test_has_gasdens
    self.d.fluids["gas"].get("2d", "mass density", 1)
  File "/home/rometsch/repo/simdata/src/simdata/fluid.py", line 23, in get
    loader = self._get_loader(geometry, name)
  File "/home/rometsch/repo/simdata/src/simdata/fluid.py", line 33, in _get_loader
    return self.variable_loaders[geometry][name]
KeyError: 'dens'`

**Comment by Astroprog** [comment]
The initialisation of the alias object and the alias_dict variable in fluid.py and alias.py were still persistent, hence the key error originating from the aliases of test_loader_fargocpt in test_loader_PLUTO42.

All tests should pass now

**Pull request merged**
