### PR TITLE
Pluto can now return temperature by reading pressure and density.

### PR DESCRIPTION
**Pull request by alexziab**
The mean molecular weight can be set with fluid.mean_mol_weight before using get(). Default is 2.353

### CODE REVIEW

**Comment by rometsch** [comment]
Three comments on the new feature:

1) load_data of the 2D field loader got quite long and it takes a long time to understand it.
Maybe you can move the calculation of the temperature and the memmap loading to a separate function. This would greatly improve readability.

2) I could not find a test checking whether the calculation is correct. If you add this, I can do the refractoring connected to 1).

3) Calculating quantities if not present in the data is definitely a great feature. However, this package is intended to only give an interface to access the data that's available. I think, we need the functionality which your feature provides, but I'd rather put this in an extra package.

**Comment by alexziab** [comment]
Btw, I would not create a new package but rather a module, since the data output right now is packed in simdata format. The current package can resolve stuff such as EOS, units, etc., and a brand new package that just converts quantities would have to re-implement all of this. Instead, I suggest a simdata module (from simdata import quantities or sth) that either inherits all the information available to the loader or just has access to them if, say, the list of fields + units + parameters is passed (which I would avoid because the module would then end up being its own package and we would end up back to the problems addressed above).

My issue is that I didn't use classes until recently so idk how to pass the loader's information to the converter module (given what I've already implemented in PLUTO42, the rest is just moving the converter function outside of the class!). As a bonus, the converter is (currently) agnostic of code, which motivates making this a shared simdata module.

So, yeah, if someone can create the environment (pass the loader's info to a class in a different module that I can then start adding quantities to), then I can migrate everything from the PLUTO42 loader to there!

**Comment by rometsch** [comment]
Thanks for implementing all the request. It looks much clearer now. The test also runs on my computer so it should be safe to merge :)

**Comment by rometsch** [comment]
Concerning the module vs package question:
Information like EOS, units and so on should actually be exposed via the Data object. Providing these information (alongside the physical quantities) in a code independent way is its purpose.
So another package could then rely on how simdata exposes these information.

But before this can be done in a separate package or module, the information needs to be provided properly by simdata. I suggest to come back to this after providing parameters and some physics information.

**Pull request merged**
